- name: Install and Start Slurm
  hosts: host-node
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install Slurm
      ansible.builtin.apt:
        name:
          - slurm-wlm
        state: present
