- name: Update and Install Packages on public Node
  hosts: public_node
  tasks:
    - name: Copy private ssh key to the machine
      ansible.builtin.copy:
        src: ../keys/aws-private-cluster-key
        dest: ~/.ssh/
        mode: '0600'

    - name: Copy public ssh key to the machine
      ansible.builtin.copy:
        src: ../keys/aws-private-cluster-key.pub
        dest: ~/.ssh/
        mode: '0644'

    - name: Allow nodes to ssh into this host node
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '../keys/nodekey.pub') }}"

    - name: Apt update
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Apt upgrade
      become: true
      ansible.builtin.apt:
        upgrade: dist

    - name: Install Slurm and other needed packages
      become: true
      ansible.builtin.apt:
        name:
          - slurm-wlm
          - munge
          - slurm
          - slurmctld
        state: present

    - name: Copy hosts file onto the machine
      become: true
      ansible.builtin.copy:
        src: hosts/hosts
        dest: /etc/hosts
        owner: ubuntu
        group: ubuntu
        mode: '0666'

    - name: Update /etc/hostname
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: '^ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+$'
        line: "{{ inventory_hostname }}"
        backup: true

    - name: Reboot the system
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 90

    - name: Copy slurm.conf
      become: true
      ansible.builtin.copy:
        src: slurmconfigs/slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: ubuntu
        group: ubuntu
        mode: '0666'

    - name: Copy cgroups.conf
      become: true
      ansible.builtin.copy:
        src: slurmconfigs/cgroups.conf
        dest: /etc/slurm/cgroups.conf
        owner: ubuntu
        group: ubuntu
        mode: '0666'

    - name: Copy cgroup_allowed_devices_file.conf
      become: true
      ansible.builtin.copy:
        src: slurmconfigs/cgroup_allowed_devices_file.conf
        dest: /etc/slurm/cgroup_allowed_devices_file.conf
        owner: ubuntu
        group: ubuntu
        mode: '0666'

    - name: Set slurm log directory with correct permissions
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '777'
      with_items:
        - /var/spool
        - /var/log/slurm

    - name: Start munge
      become: true
      ansible.builtin.systemd:
        name: munge.service
        state: started
        enabled: true

    - name: Get the munge key from head node
      become: true
      ansible.builtin.fetch:
        src: /etc/munge/munge.key
        dest: ../keys/mungekeys


    - name: Restart munge
      become: true
      ansible.builtin.systemd:
        name: munge.service
        state: restarted

    - name: Start the slurmctld
      become: true
      ansible.builtin.systemd:
        name: slurmctld
        state: started
        enabled: true
